/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://6dlmqgvbqjgixfu27fwvusibnu.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-t6vm47pm4jaabe2tqvpzpljrye",
    "aws_cognito_identity_pool_id": "us-west-2:b519fe94-8336-4040-9d22-514146bf3c64",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_rn8DUQhw1",
    "aws_user_pools_web_client_id": "6ilb84sgnoq3e2pbhob8fpe7k3",
    "oauth": {},
    "aws_user_files_s3_bucket": "socialmediaappfc9c9c2a2621401faa926b241321573d33526-dev",
    "aws_user_files_s3_bucket_region": "us-west-2",
    "aws_mobile_analytics_app_id": "1ed59e0e8efc4ab5b1cc03c668e27397",
    "aws_mobile_analytics_app_region": "us-west-2",
    "predictions": {
        "identify": {
            "identifyLabels": {
                "proxy": false,
                "region": "us-west-2",
                "defaults": {
                    "type": "LABELS"
                }
            }
        }
    }
};


export default awsmobile;
